// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8iwnCku4WpguXUu9FiPMEj6sLuGQ8HgM',
    appId: '1:627771756883:web:bcd47a9361904af00e91a6',
    messagingSenderId: '627771756883',
    projectId: 'fribaseintroduction',
    authDomain: 'fribaseintroduction.firebaseapp.com',
    storageBucket: 'fribaseintroduction.appspot.com',
    measurementId: 'G-F6NGHFXXY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB30SD4xndjjZS7-GlblXAg3P-qVQAIfs',
    appId: '1:627771756883:android:e869a84f17d9342e0e91a6',
    messagingSenderId: '627771756883',
    projectId: 'fribaseintroduction',
    storageBucket: 'fribaseintroduction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqhWoScXIW8R3nLyvvtL8Sp8SVEHSw-bk',
    appId: '1:627771756883:ios:c95ba08e5ed80b7d0e91a6',
    messagingSenderId: '627771756883',
    projectId: 'fribaseintroduction',
    storageBucket: 'fribaseintroduction.appspot.com',
    iosBundleId: 'com.example.firebaseIntroduction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqhWoScXIW8R3nLyvvtL8Sp8SVEHSw-bk',
    appId: '1:627771756883:ios:5c6976ef6b005e6a0e91a6',
    messagingSenderId: '627771756883',
    projectId: 'fribaseintroduction',
    storageBucket: 'fribaseintroduction.appspot.com',
    iosBundleId: 'com.example.firebaseIntroduction.RunnerTests',
  );
}
